# Site settings
title: "Fengz 的自言自语"
description: ""
keywords: "umzulu"
author:
    name: umzulu
    github: umzulu
    email:   
    twitter: zhchf
    facebook:
    googleplus:
    weibo: zhchfddup
highlighter: pygments
#pygments: false
#highlighter: rouge
markdown: redcarpet
redcarpet:
    extensions: ["fenced_code_blocks", "tables", "highlight", "strikethrough"]
paginate: 10
permalink: pretty
cdn: http://fengz.qiniudn.com   
comments:
    duoshuo:
        name: umzulu 
        rcomments:
            num: 10
            avatar: 1
            time: 1
            title: 1
            admin: 1
            length: 30
